# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.createCStruct <- function(a, b) {
    .Call(`_RCStruct_createCStruct`, a, b)
}

.updateCStruct <- function(obj, a, b) {
    .Call(`_RCStruct_updateCStruct`, obj, a, b)
}

.showCStruct <- function(obj) {
    invisible(.Call(`_RCStruct_showCStruct`, obj))
}

.addCStruct <- function(obj1, obj2) {
    .Call(`_RCStruct_addCStruct`, obj1, obj2)
}

.subCStruct <- function(obj1, obj2) {
    .Call(`_RCStruct_subCStruct`, obj1, obj2)
}

.eqCStruct <- function(obj1, obj2) {
    .Call(`_RCStruct_eqCStruct`, obj1, obj2)
}

.difCStruct <- function(obj1, obj2) {
    .Call(`_RCStruct_difCStruct`, obj1, obj2)
}

